### ISSUE TITLE
Files aren't uploaded on the selected container

### ISSUE THREAD

**Issue by Erethon** [olgabrani/synnefo#150] opened 2015-05-06 09:37 UTC
Steps to reproduce:

```
1) Select container 'A'
2) Select container 'B'
3) Upload a file
```

The file will be uploaded on container 'A' instead of container 'B'

**Comment by vinilios** [comment] 2015-06-10 11:04
Cannot reproduce. It seems that this have been unintentionally fixed on a recent commit. Closing the issue for the time being.

**Closed as completed by vinilios** 2015-06-10 11:04 UTC
